### ISSUE TITLE
Error when loading FluidSynth.clap on Windows 10

### ISSUE THREAD

**Issue by JBetz** [cannerycoders/fluidsynth.clap#1]
The error message is: `LoadLibrary: invalid argument (The specified procedure could not be found.)`. I added the `FluidSynth.clap` directory to PATH and verified that all the necessary DLLs are available using [Dependencies](https://github.com/lucasg/Dependencies), but still no joy.

Any ideas on how to troubleshoot this?

Some context: I'm implementing [an audio engine in Haskell](https://github.com/JBetz/ensemble) and would love to be able use this plugin for Soundfont playback. For CLAP hosting, I've been using [clap-host](https://github.com/free-audio/clap-host) as a reference, and so far have been able to get [clap-saw-demo](https://github.com/surge-synthesizer/clap-saw-demo) and Vital working, but not FluidSynth.clap.

Platform: Windows 10 (64-bit)
Version: 0.2.1

**Comment by dbadb** [comment]
If you have control over your c++ code (or whatever invokes LoadLibrary) there's a magic call to add... here's a snippet:

```cpp
    std::filesystem::path p(dllpath); //
    std::filesystem::path parent(p.parent_path());
    SetDllDirectory(parent.generic_string().c_str());
    void *x = (void *) LoadLibrary(dllpath);
```

I'm looking at migrating to static-linked libraries for windows but I'm curious if this works for you.

**Comment by JBetz** [comment]
Yup, that worked. Thanks!
